### ISSUE TITLE
import kaldifeat error

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/sherpa#8] opened 2022-06-01 07:09 UTC
Now, I follow the streaming mode in the sherpa. When I install kaldifeat, it doesn't occur error, however, I use it, and occurs the below errors, I have no idea.

```
k2-fsa-stream2) root@2609bb264fa5:/mnt/4T_b/md/k2_recipe/sherpa# pip install -v --no-cache-dir kaldifeat 
Using pip 21.2.4 from /opt/conda/envs/k2-fsa-stream2/lib/python3.8/site-packages/pip (python 3.8)
Requirement already satisfied: kaldifeat in /opt/conda/envs/k2-fsa-stream2/lib/python3.8/site-packages (1.15)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(k2-fsa-stream2) root@2609bb264fa5:/mnt/4T_b/md/k2_recipe/sherpa# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaldifeat import FbankOptions, OnlineFbank, OnlineFeature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/k2-fsa-stream2/lib/python3.8/site-packages/kaldifeat/__init__.py", line 2, in <module>
    from _kaldifeat import (
ImportError: /opt/conda/envs/k2-fsa-stream2/lib/python3.8/site-packages/libkaldifeat_core.so: undefined symbol: _ZNK2at6Tensor4meanEN3c108ArrayRefIlEEbNS1_8optionalINS1_10ScalarTypeEEE

```

**Comment by csukuangfj** [comment] 2022-06-01 07:14
Can you check that the version of PyTorch you used to install kaldifeat is the same version you are currently using?

**Comment by csukuangfj** [comment] 2022-06-01 07:25
The easiest thing is to reinstall kaldifeat.

I will try to update kaldifeat to detect such kind of errors during import.

**Comment by shanguanma** [comment] 2022-06-01 07:34
OK,  thanks a lot. I will reinstall it new environment,

**Comment by csukuangfj** [comment] 2022-06-01 11:05
>  each time I struggled with installing kaldifeat because of pytorch/cuda/cudnn versions etc..

Could you please post the errors so that I can fix it in kaldifeat?

**Comment by csukuangfj** [comment] 2022-06-04 10:57
The latest version of kaldifeat should report such kind of mismatch during import time. Closing.

**Closed by csukuangfj** 2022-06-04 10:57 UTC

**Comment by EmreOzkose** [comment] 2022-06-08 12:04
The problem is creating an environment from scratch. If I create an environment and run `pip install requirements.txt`, it is not installing torch before. Informative part of error log:

```
Installing collected packages: sentencepiece, websockets, kaldifeat
  Running setup.py install for kaldifeat ... error
  error: subprocess-exited-with-error

  × Running setup.py install for kaldifeat did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      running install
      /path/to/miniconda3/envs/sherpa/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/offline_feature.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/online_feature.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/plp.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/spectrogram.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/mfcc.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/__init__.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      copying kaldifeat/python/kaldifeat/fbank.py -> build/lib.linux-x86_64-cpython-38/kaldifeat
      running build_ext
      Setting PYTHON_EXECUTABLE to /path/to/miniconda3/envs/sherpa/bin/python3.8
      For fast compilation, run:
      export KALDIFEAT_MAKE_ARGS="-j"; python setup.py install
      build command is:

                      cd build/temp.linux-x86_64-cpython-38

                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/path/to/miniconda3/envs/sherpa/bin/python3.8 /tmp/pip-install-paz8x5tn/kaldifeat_1678274386b64d78a6ac5ebd77296eb2


                      make  _kaldifeat

      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- C++ Standard version: 14
      -- Downloading pybind11
      -- pybind11 is downloaded to /tmp/pip-install-paz8x5tn/kaldifeat_1678274386b64d78a6ac5ebd77296eb2/build/temp.linux-x86_64-cpython-38/_deps/pybind11-src
      -- pybind11 v2.9.2
      -- Found PythonInterp: /path/to/miniconda3/envs/sherpa/bin/python3.8 (found version "3.8.13")
      -- Found PythonLibs: /path/to/miniconda3/envs/sherpa/lib/libpython3.8.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Python executable: /path/to/miniconda3/envs/sherpa/bin/python3.8
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'torch'
      CMake Error at cmake/torch.cmake:13 (find_package):
        By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Torch", but
        CMake did not find one.

        Could not find a package configuration file provided by "Torch" with any of
        the following names:

          TorchConfig.cmake
          torch-config.cmake

        Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
        "Torch_DIR" to a directory containing one of the above files.  If "Torch"
        provides a separate development package or SDK, be sure it has been
        installed.
      Call Stack (most recent call first):
        CMakeLists.txt:48 (include)
```

So, first, Kaldifeat should be installed with `conda install -c kaldifeat -c pytorch -c conda-forge kaldifeat python=3.8 cudatoolkit=11.1 pytorch=1.8.1` and then run `pip install -r requirements.txt`.

**Comment by csukuangfj** [comment] 2022-06-08 12:10
> The problem is creating an environment from scratch. If I create an environment and run pip install requirements.txt

Please first install PyTorch before installing kaldifeat or sherpa.

This page
https://k2-fsa.github.io/sherpa/installation/from-source.html
has detailed installation instructions.
