### ISSUE TITLE
install new version of sherpa

### ISSUE THREAD

**Issue by alidabaghi** [k2-fsa/sherpa#356] opened 2023-04-03 10:35 UTC
hello. i am trying to install new version of sherpa and occurance this error?
![Screenshot from 2023-04-03 14-01-34](https://user-images.githubusercontent.com/78419335/229485738-d092c25c-f20d-4780-bf18-09408722ec17.png)

**Comment by csukuangfj** [comment] 2023-04-03 10:37
@alidabaghi 
Could you try the latest master?

It should have been fixed by
https://github.com/k2-fsa/sherpa/pull/355

**Comment by alidabaghi** [comment] 2023-04-03 11:52
i am recloning in master and occurance this error new?
![Screenshot from 2023-04-03 15-19-59](https://user-images.githubusercontent.com/78419335/229501463-53bd8609-a94c-44e8-9a6f-5ec632eb6606.png)

**Comment by alidabaghi** [comment] 2023-04-03 11:58
Can you help me?

**Comment by csukuangfj** [comment] 2023-04-03 12:07
Could you please show the output of the following command 

make VERBOSE=1

**Comment by alidabaghi** [comment] 2023-04-03 12:13
![Screenshot from 2023-04-03 15-43-05](https://user-images.githubusercontent.com/78419335/229505722-893186a1-aaaf-4a7e-8cc5-6763bf9926d8.png)

**Comment by alidabaghi** [comment] 2023-04-03 12:18
fig above

**Comment by csukuangfj** [comment] 2023-04-03 12:55
@alidabaghi 
Sorry, I cannot reproduce your issue.

As a workaround, could you change
https://github.com/k2-fsa/sherpa/blob/a04ed8454ccab5284aef1306efccc397f8f20341/sherpa/cpp_api/bin/CMakeLists.txt#L2
to
```cmake
target_link_libraries(sherpa-offline sherpa_cpp_api -pthread)
```
and re-try?

**Comment by alidabaghi** [comment] 2023-04-03 13:35
Thank you so much for your help and support. I really appreciate it.

**Comment by alidabaghi** [comment] 2023-04-03 14:04
yes.
My goal is to add a zipformer model for this code.
https://github.com/k2-fsa/sherpa/blob/master/sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py

**Comment by alidabaghi** [comment] 2023-04-04 05:48
excuse me. i am trying add zipformer model to sherpa for test in front. Can I do this?

**Comment by csukuangfj** [comment] 2023-04-04 06:46
Yes, absolutely you can do it.

**Comment by csukuangfj** [comment] 2023-04-04 07:21
> excuse me. i am trying add zipformer model to sherpa for test in front. Can I do this?

Please post any issues if you have.

**Comment by csukuangfj** [comment] 2023-04-17 13:37
> excuse me. i am trying add zipformer model to sherpa for test in front. Can I do this?

@alidabaghi 
Please see https://github.com/k2-fsa/sherpa/pull/365

**Closed** 2023-04-17 13:36 UTC
